const reservedWords = {
    regexp: "`/(?<=\\\\s)${key}(?=[\\\\s:])/gm`",
    safariReg: "`/${key}(?=[\\\\s:])/gm`",
    words: {
        "kw_print" : "畀我睇下",
        "kw_endprint" : "点样先",
        "kw_exit" : "收工",
        "kw_in" : "喺",
        "kw_elif" : "定系",
        "kw_turtle_beg" : "老作一下",
        "kw_type" : "起底",
        "kw_assign" : "讲嘢",
        "kw_class_def" : "咩系",
        "kw_else_or_not" : "唔系",
        "kw_is" : "系",
        "kw_if" : "如果",
        "kw_then" : "嘅话",
        "kw_do" : "->",
        "kw_begin" : "{",
        "kw_end" : "}",
        "kw_pass" : "咩都唔做",
        "kw_while_do" : "落操场玩跑步",
        "kw_function" : "$",
        "kw_call" : "用下",
        "kw_import" : "使下",
        "kw_func_begin" : "要做咩",
        "kw_func_end" : "搞掂",
        "kw_is_2" : "就",
        "kw_assert" : "谂下",
        "kw_class_assign" : "佢嘅",
        "kw_while" : "玩到",
        "kw_whi_end" : "为止",
        "kw_return" : "还数",
        "kw_try": "执嘢",
        "kw_except" : "揾到",
        "kw_finally" : "执手尾",
        "kw_raise" : "掟个",
        "kw_raise_end" : "来睇下",
        "kw_from" : "从",
        "kw_to" : "行到",
        "kw_endfor" : "行晒",
        "kw_extend" : "佢个老豆叫",
        "kw_method" : "佢识得",
        "kw_endclass" : "明白未啊",
        "kw_cmd" : "落Order",
        "kw_break" : "饮茶先啦",
        "kw_lst_assign" : "拍住上",
        "kw_set_assign" : "埋堆",
        "kw_global_set" : "Share下",
        "kw_is_3" : "係",
        "kw_exit_1" : "辛苦晒啦",
        "kw_exit_2" : "同我躝",
        "kw_false" : "唔啱",
        "kw_true" : "啱",
        "kw_none" : "冇",
        "kw_stackinit" : "有条仆街叫",
        "kw_push" : "顶你",
        "kw_pop" : "丢你",
        "kw_model" : "嗌",
        "kw_mod_new" : "过嚟估下",
        "kw_class_init" : "佢有啲咩",
        "kw_self" : "自己嘅",
        "kw_call_begin" : "下",
        "kw_get_value" : "@" ,
    }
}

const keywords = [reservedWords]

export {keywords}
